name: climate_pretrain
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asciitree=0.3.3=py_2
  - attrs=21.4.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bokeh=2.4.3=py38h578d9bd_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py38h578d9bd_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=4.12.0=py38h578d9bd_0
  - conda-package-handling=1.8.1=py38h7f8727e_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.7.1=pyhd8ed1ab_0
  - distributed=2022.7.1=pyhd8ed1ab_0
  - einops=0.4.1=pyhd8ed1ab_0
  - esmf=8.2.0=mpi_mpich_h4975321_100
  - esmpy=8.2.0=mpi_mpich_py38h9147699_101
  - fasteners=0.16.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - fire=0.4.0=pyh44b312d_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=mpi_mpich_h9c45103_0
  - heapdict=1.0.1=py_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.5.2=h5de8990_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libmamba=0.22.1=hd8a31e3_1
  - libmambapy=0.22.1=py38h923e62a_1
  - libnetcdf=4.8.1=mpi_mpich_h319fa22_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsolv=0.7.20=h4ff587b_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - libzip=1.8.0=h5cef20c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.0.0=py38h1bf946c_2
  - lz4-c=1.9.3=h295c915_1
  - mamba=0.22.1=py38h1abaa86_1
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpi=1.0=mpich
  - mpi4py=3.1.3=py38h97ac3a3_1
  - mpich=4.0.2=h846660c_100
  - msgpack-python=1.0.3=py38hd09550d_0
  - munkres=1.1.4=py_0
  - mypy=0.910=pyhd3eb1b0_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - ncurses=6.3=h7f8727e_2
  - netcdf-fortran=4.5.4=mpi_mpich_h1364a43_0
  - nettle=3.7.3=hbbd107a_1
  - numcodecs=0.9.1=py38h295c915_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathspec=0.7.0=py_0
  - patsy=0.5.2=py38h06a4308_1
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py38h06a4308_0
  - pyyaml=6.0=py38h0a891b7_4
  - readline=8.1.2=h7f8727e_1
  - regex=2022.3.15=py38h7f8727e_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.27.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scipy=1.8.1=py38h1ee437e_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.38.3=hc218d9a_0
  - statsmodels=0.13.2=py38h7f8727e_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - termcolor=1.1.0=py38h06a4308_1
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py38_cu113
  - torchdata=0.3.0=py38
  - torchvision=0.12.0=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.64.0=py38h06a4308_0
  - typed-ast=1.4.3=py38h7f8727e_1
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.9=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xesmf=0.3.0=py_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.6.3=he1b5a44_4
  - zarr=2.8.1=pyhd3eb1b0_0
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.0=py38h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.1.0
    - adal==1.2.7
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - applicationinsights==0.11.10
    - argcomplete==2.0.0
    - async-timeout==4.0.2
    - azure-common==1.1.28
    - azure-core==1.24.2
    - azure-graphrbac==0.61.1
    - azure-identity==1.7.0
    - azure-mgmt-authorization==2.0.0
    - azure-mgmt-containerregistry==10.0.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==10.0.0
    - azure-mgmt-resource==21.1.0
    - azure-mgmt-storage==20.0.0
    - azureml-core==1.43.0
    - azureml-dataprep==4.0.4
    - azureml-dataprep-native==38.0.0
    - azureml-dataprep-rslex==2.6.3
    - azureml-dataset-runtime==1.43.0
    - azureml-defaults==1.43.0
    - azureml-inference-server-http==0.4.13
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.2
    - cachetools==5.2.0
    - cdsapi==0.5.1
    - cfgv==3.3.1
    - cftime==1.6.0
    - click==7.1.2
    - commonmark==0.9.1
    - configparser==3.7.4
    - contextlib2==21.6.0
    - dask==2022.6.1
    - decorator==5.1.1
    - deepspeed==0.7.0
    - distlib==0.3.4
    - distro==1.7.0
    - docker==5.0.3
    - docstring-parser==0.14.1
    - dotnetcore2==3.1.23
    - filelock==3.7.1
    - flask==1.0.3
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - fusepy==3.0.1
    - gcsfs==2022.5.0
    - google-api-core==2.8.2
    - google-auth==2.7.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.1
    - google-cloud-storage==2.4.0
    - google-crc32c==1.3.0
    - google-resumable-media==2.3.3
    - googleapis-common-protos==1.56.3
    - grpcio==1.46.3
    - gunicorn==20.1.0
    - hjson==3.0.2
    - humanfriendly==10.0
    - hydra-core==1.2.0
    - identify==2.5.1
    - imageio==2.19.3
    - importlib-resources==5.8.0
    - inference-schema==1.3.0
    - iniconfig==1.1.1
    - isodate==0.6.1
    - isort==5.10.1
    - itsdangerous==1.1.0
    - jeepney==0.8.0
    - jinja2==3.0.3
    - jmespath==1.0.0
    - json-logging-py==0.2
    - jsonargparse==4.9.0
    - jsonpickle==2.2.0
    - jsonschema==4.6.1
    - kiwisolver==1.4.3
    - knack==0.9.0
    - markdown==3.3.7
    - matplotlib==3.5.2
    - mccabe==0.6.1
    - mpmath==1.2.1
    - msal==1.18.0
    - msal-extensions==0.3.1
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multidict==6.0.2
    - myaml==1.0.1
    - ndg-httpsclient==0.5.1
    - netcdf4==1.6.0
    - ninja==1.10.2.3
    - nodeenv==1.6.0
    - oauthlib==3.2.0
    - omegaconf==2.2.2
    - opencensus==0.10.0
    - opencensus-context==0.1.2
    - opencensus-ext-azure==1.1.5
    - pandas==1.4.3
    - paramiko==2.11.0
    - pkginfo==1.8.3
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - portalocker==2.5.1
    - pre-commit==2.19.0
    - protobuf==3.19.4
    - py==1.11.0
    - py-cpuinfo==8.0.0
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.1
    - pydeprecate==0.3.2
    - pygments==2.12.0
    - pyjwt==2.4.0
    - pynacl==1.5.0
    - pyrsistent==0.18.1
    - pytest==7.1.2
    - pytorch-lightning==1.6.5
    - pytorch-pfn-extras==0.5.8
    - requests-oauthlib==1.3.1
    - rich==12.4.1
    - rsa==4.8
    - secretstorage==3.3.2
    - sh==1.14.2
    - sympy==1.10.1
    - tabulate==0.8.10
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - timm==0.5.4
    - tomli==2.0.1
    - toolz==0.11.2
    - torchmetrics==0.9.1
    - virtualenv==20.14.1
    - websocket-client==1.3.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xarray==2022.3.0
    - yarl==1.7.2
    